# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exercise2-TextureLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Exercise2-TextureLibrary
  pod 'Texture'
  pod 'ReSwift'
  pod 'ReSwiftThunk'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'	
#  pod 'JWTDecode'
end
